#ifndef GAME_CONSTANTS_H_INCLUDED
#define GAME_CONSTANTS_H_INCLUDED

const int NUM_AGES = 3;
const int COINS_PER_SCORE = 3;
const int SCORE_PER_LOSS = -1;
const int SCORE_PER_WIN[NUM_AGES] = {1, 3, 5};
const int SCORE_PER_SCI_COMBO = 7;

#endif // GAME_CONSTANTS_H_INCLUDED
